/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AImage: typeof import('ant-design-vue/es')['Image']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATag: typeof import('ant-design-vue/es')['Tag']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    AUploadDragger: typeof import('ant-design-vue/es')['UploadDragger']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Upload: typeof import('./src/components/Upload.vue')['default']
  }
}
